# Bootstrapping

In [1]:
import xarray as xr
import numpy as np

In [2]:
from xbootstrap import block_bootstrap

In [3]:
import dask.array

# Test

In [8]:
def test_block_bootstrap_output_type(data, blocks, n_iteration):
    """Test that output type is correct"""
    shape = data.shape
    x = xr.DataArray(
        data,
        coords={f"d{i}": range(shape[i]) for i in range(len(shape))},
    )
    out = block_bootstrap(x, blocks={"d0": blocks}, n_iteration=n_iteration)
    assert isinstance(out, xr.DataArray)
    out = block_bootstrap(x, x, blocks={"d0": blocks}, n_iteration=n_iteration)
    assert isinstance(out, tuple)

In [9]:
np_arr = np.zeros(shape=(10, 5))

In [10]:
shape = (240, 240, 240)

darray = dask.array.zeros(shape, chunks=(-1, -1, -1))

In [11]:
blocks = [1, 3]
n_iteration = [1, 2]

In [12]:
for arr in [np_arr, darray]:
    for b in blocks:
        for n_iter in n_iteration:
            test_block_bootstrap_output_type(data=arr, blocks=b, n_iteration=n_iter)

### From previous code:

In [54]:
test_block_bootstrap_output_type()

TypeError: concat() got multiple values for argument 'dim'

# Sandpit

In [18]:
x = np.random.choice(5, size=(3, 3, 3))

In [19]:
da = xr.DataArray(
    x,
    coords={'x': range(3), 'y': range(3), 't': range(3)}
)

In [21]:
x

array([[[4, 2, 2],
        [0, 4, 4],
        [0, 0, 0]],

       [[4, 4, 4],
        [1, 3, 2],
        [1, 4, 3]],

       [[3, 4, 1],
        [3, 2, 1],
        [1, 3, 3]]])

In [25]:
bs = block_bootstrap(
    da,da,
    blocks={"t": 1},
    n_iteration=1
)

In [27]:
bs[0]

<xarray.DataArray (x: 3, y: 3, t: 3, iteration: 1)>
array([[[[2],
         [2],
         [4]],

        [[4],
         [4],
         [0]],

        [[0],
         [0],
         [0]]],


       [[[4],
         [4],
         [4]],

        [[3],
         [3],
         [1]],

        [[4],
         [4],
         [1]]],


       [[[4],
         [4],
         [3]],

        [[2],
         [2],
         [3]],

        [[3],
         [3],
         [1]]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1 2
  * t        (t) int64 0 1 2
Dimensions without coordinates: iteration

In [28]:
bs[1]

<xarray.DataArray (x: 3, y: 3, t: 3, iteration: 1)>
array([[[[2],
         [2],
         [4]],

        [[4],
         [4],
         [0]],

        [[0],
         [0],
         [0]]],


       [[[4],
         [4],
         [4]],

        [[3],
         [3],
         [1]],

        [[4],
         [4],
         [1]]],


       [[[4],
         [4],
         [3]],

        [[2],
         [2],
         [3]],

        [[3],
         [3],
         [1]]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1 2
  * t        (t) int64 0 1 2
Dimensions without coordinates: iteration